[package]
name = "sleef"
edition = "2018"
version = "0.1.0"
authors = ["Andrey Zgarbul <zgarbul.andrey@gmail.com>"]

[dependencies.doubled]
git = "https://github.com/burrbull/doubled-rs"
features = ["packed_simd"]

[dependencies.packed_simd]
version = "0.3.3"
features = ["into_bits"]

[features]
default = []
deterministic = []
std = []
fasttest = []

[dev-dependencies]
rand = "0.6"
libm = "0.1.3"
