[package]
name = "sleef"
edition = "2018"
version = "0.1.0"
authors = ["Andrey Zgarbul <zgarbul.andrey@gmail.com>"]

[dependencies.doubled]
git = "https://github.com/burrbull/doubled-rs"
features = ["packed_simd"]

[dependencies.packed_simd]
#version = "0.3"
git = "https://github.com/rust-lang-nursery/packed_simd"
features = ["into_bits"]

[features]
default = []
deterministic = []
