[package]
name = "sleef"
edition = "2018"
version = "0.1.0"
authors = ["Andrey Zgarbul <zgarbul.andrey@gmail.com>"]

[dependencies.doubled]
version = "0.2"
features = ["packed_simd"]

[dependencies.packed_simd]
package = "packed_simd_2"
version = "0.3.8"
features = ["into_bits"]

[features]
default = []
deterministic = []

[dev-dependencies]
rug = "1.16"

[dev-dependencies.rand]
version = "0.8.5"
features = ["simd_support"]
