[package]
name = "shared"
version = "0.1.0"
authors = ["Jorge Aparicio <jorge@japaric.io>"]

[dependencies]
lazy_static = "1.0.2"

[dependencies.packed_simd]
version = "0.3.2"
features = ["into_bits"]
